# embed_skills.cmake — reads SKILL.md files from references/ and writes
# src/generated/skill_content.h with one constexpr char[] per skill.
#
# Invoked as: cmake -DOUTPUT_FILE=<path> -DREFS_DIR=<path> -P embed_skills.cmake

cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED OUTPUT_FILE OR NOT DEFINED REFS_DIR)
    message(FATAL_ERROR "Usage: cmake -DOUTPUT_FILE=<out.h> -DREFS_DIR=<refs/> -P embed_skills.cmake")
endif()

message(STATUS "embed_skills: generating ${OUTPUT_FILE}")

# Write header
file(WRITE "${OUTPUT_FILE}"
"// AUTO-GENERATED by scripts/embed_skills.cmake — do not edit manually.\n"
"#pragma once\n"
"\n"
"// Suppress MSVC C4838/C4309: narrowing int->char for high bytes (UTF-8 content)\n"
"#ifdef _MSC_VER\n"
"#  pragma warning(push)\n"
"#  pragma warning(disable: 4309 4838)\n"
"#endif\n"
"\n"
)

# ── Skill list: ID, PascalName, path-relative-to-REFS_DIR ────────────────────
# Each triple is stored in three parallel lists.

set(SKILL_IDS
    "caveman"
    "caveman-commit"
    "caveman-compress"
    "caveman-help"
    "caveman-review"
    "caveman-stats"
    "cavecrew"
    "openspec-propose"
    "openspec-apply-change"
    "openspec-explore"
    "openspec-archive-change"
    "skill-creator"
    "pdf"
    "pptx"
    "docx"
    "xlsx"
    "officecli"
    "canvas-design"
    "frontend-design"
)

set(SKILL_PASCALS
    "Caveman"
    "CavemanCommit"
    "CavemanCompress"
    "CavemanHelp"
    "CavemanReview"
    "CavemanStats"
    "Cavecrew"
    "OpenspecPropose"
    "OpenspecApplyChange"
    "OpenspecExplore"
    "OpenspecArchiveChange"
    "SkillCreator"
    "Pdf"
    "Pptx"
    "Docx"
    "Xlsx"
    "Officecli"
    "CanvasDesign"
    "FrontendDesign"
)

set(SKILL_PATHS
    "Agentic Skills/caveman/skills/caveman/SKILL.md"
    "Agentic Skills/caveman/skills/caveman-commit/SKILL.md"
    "Agentic Skills/caveman/skills/caveman-compress/SKILL.md"
    "Agentic Skills/caveman/skills/caveman-help/SKILL.md"
    "Agentic Skills/caveman/skills/caveman-review/SKILL.md"
    "Agentic Skills/caveman/skills/caveman-stats/SKILL.md"
    "Agentic Skills/caveman/skills/cavecrew/SKILL.md"
    "BillingPlatform/.github/skills/openspec-propose/SKILL.md"
    "BillingPlatform/.github/skills/openspec-apply-change/SKILL.md"
    "BillingPlatform/.github/skills/openspec-explore/SKILL.md"
    "BillingPlatform/.github/skills/openspec-archive-change/SKILL.md"
    "BillingPlatform/.github/skills/skill-creator/SKILL.md"
    "BillingPlatform/.github/skills/pdf/SKILL.md"
    "BillingPlatform/.github/skills/pptx/SKILL.md"
    "BillingPlatform/.github/skills/docx/SKILL.md"
    "BillingPlatform/.github/skills/xlsx/SKILL.md"
    "BillingPlatform/.github/skills/officecli/SKILL.md"
    "BillingPlatform/.github/skills/canvas-design/SKILL.md"
    "BillingPlatform/.github/skills/frontend-design/SKILL.md"
)

list(LENGTH SKILL_IDS skill_count)
math(EXPR last_idx "${skill_count} - 1")

foreach(i RANGE ${last_idx})
    list(GET SKILL_IDS    ${i} skill_id)
    list(GET SKILL_PASCALS ${i} pascal)
    list(GET SKILL_PATHS   ${i} rel_path)

    set(full_path "${REFS_DIR}/${rel_path}")

    if(EXISTS "${full_path}")
        # Read as hex bytes to avoid MSVC C2026 "string too big" (65535 byte limit)
        file(READ "${full_path}" hex_content HEX)
        # Convert hex pairs to 0xNN, format: "48656c6c6f" -> "0x48,0x65,0x6c,0x6c,0x6f,"
        string(REGEX REPLACE "(..)" "0x\\1," hex_c "${hex_content}")
        file(APPEND "${OUTPUT_FILE}"
            "static const char k${pascal}Content[] = {\n${hex_c}0x00};\n\n")
        message(STATUS "  embed: ${skill_id}")
    else()
        message(WARNING "  embed: MISSING ${full_path}")
        file(APPEND "${OUTPUT_FILE}"
            "static const char k${pascal}Content[] = {0x00}; /* SKILL.md not found: ${rel_path} */\n\n")
    endif()
endforeach()

message(STATUS "embed_skills: done (${skill_count} skills)")

file(APPEND "${OUTPUT_FILE}"
"#ifdef _MSC_VER\n"
"#  pragma warning(pop)\n"
"#endif\n"
)
